WebApplication4/src/WebApplication4/ViewModels/ComponentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApplication4.ViewModels
{
    public class ComponentViewModel
    {

        public int ComponentId { set; get; }
        public int ComponentNumber { set; get; }
        public string SerialNo { set; get; }
        public string AdminComment { set; get; }

        public List<SelectListItem> Status { set; get; }
        public string SelectedStatus { set; get; }
        public string SelectedComponentId { set; get; }

        public List<SelectListItem> ComponentTypeSelectListItems { set; get; }
        public List<SelectListItem> ComponentsSelectListItems { set; get; }

        public string SelectedComponentTypeId { set; get; }
    }
}

WebApplication4/src/WebApplication4/Controllers/ComponentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication4.Models;
using WebApplication4.ViewModels;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace WebApplication4.Controllers
{
    [Authorize(Roles = "Admins")]
    public class ComponentController : Controller
    {

        private AesContext _aesContext;

        public ComponentController(AesContext aesContext)
        {
           _aesContext = aesContext;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Edit()
        {
            var vm = EditComponentViewModel();
            return View(vm);
        }

        private ComponentViewModel EditComponentViewModel()
        {
            var componentList = _aesContext.Component.AsNoTracking().ToList();
            var vm = new ComponentViewModel();
            vm.Status = new List<SelectListItem>();
            vm.ComponentsSelectListItems = new List<SelectListItem>();
            vm.ComponentTypeSelectListItems = new List<SelectListItem>();

            foreach (var component in componentList)
            {
                vm.ComponentsSelectListItems.Add(new SelectListItem
                {
                    Text = component.SerialNo,
                    Value = component.ComponentId.ToString()
                });
            }

            foreach (var componentType in _aesContext.ComponentType.AsNoTracking().ToList())
            {
                vm.ComponentTypeSelectListItems.Add(new SelectListItem
                {
                    Text = componentType.ComponentName,
                    Value = componentType.ComponentTypeId.ToString()
                });
            }

            foreach (String component in Enum.GetNames(typeof(Category.ComponentStatus)))
            {
                vm.Status.Add(new SelectListItem
                {
                    Text = component,
                    Value = component
                });
            }
            return vm;
        }

        [HttpPost]
        public IActionResult Edit(ComponentViewModel vm)
        {
            if (ModelState.IsValid)
            {
                var foundCompoent = _aesContext.Component.FirstOrDefault(b => b.ComponentId == int.Parse(vm.SelectedComponentId));
                var foundCompoentType = _aesContext.ComponentType.FirstOrDefault(b => b.ComponentTypeId == int.Parse(vm.SelectedComponentTypeId));

                foundCompoent.SerialNo = vm.SerialNo;
                foundCompoent.AdminComment = vm.AdminComment;
                foundCompoent.ComponentTypeId = foundCompoentType.ComponentTypeId;                               

                _aesContext.Component.Update(foundCompoent);
                _aesContext.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                //Stay on page and try again.
                return View(EditComponentViewModel());
            }
        }

        public IActionResult Remove()
        {
            var vm = RenderRemoveViewModel();

            return View(vm);
        }

        private ComponentViewModel RenderRemoveViewModel()
        {
            var componentList = _aesContext.Component.ToList();
            var vm = new ComponentViewModel();
            vm.ComponentsSelectListItems = new List<SelectListItem>();

            foreach (var component in componentList)
            {
                vm.ComponentsSelectListItems.Add(new SelectListItem
                {
                    Text = component.SerialNo,
                    Value = component.ComponentId.ToString()
                });
            }
            return vm;
        }

        public IActionResult Create()
        {
            return View(CreateComponentViewModel());
        }

        private ComponentViewModel CreateComponentViewModel()
        {
            var vm = new ComponentViewModel();
            vm.Status = new List<SelectListItem>();
            vm.ComponentTypeSelectListItems = new List<SelectListItem>();

            foreach (String component in Enum.GetNames(typeof(Category.ComponentStatus)))
            {
                vm.Status.Add(new SelectListItem
                {
                    Text = component,
                    Value = component
                });
            }

            foreach (var componentType in _aesContext.ComponentType.AsNoTracking().ToList())
            {
                vm.ComponentTypeSelectListItems.Add(new SelectListItem
                {
                    Text = componentType.ComponentName,
                    Value = componentType.ComponentTypeId.ToString()
                });
            }
            return vm;
        }

        [HttpPost]
        public IActionResult Remove(ComponentViewModel vm)
        {
            if (string.IsNullOrWhiteSpace(vm.SelectedComponentId))
            {
                ModelState.AddModelError(nameof(vm.SelectedComponentId), "vælg en komponet");
            }

            if (ModelState.IsValid)
            {
                var firstOrDefault = _aesContext.Component.FirstOrDefault(b => b.ComponentId == int.Parse(vm.SelectedComponentId));
                _aesContext.Component.Remove(firstOrDefault);
                _aesContext.SaveChanges();
            }
            else
            {
                //Stay on page and try again.
                return View(RenderRemoveViewModel());
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Create(ComponentViewModel vm)
        {
            if (string.IsNullOrWhiteSpace(vm.SerialNo))
            {
                ModelState.AddModelError(nameof(vm.SerialNo),"tast et komponet serial nummer");
            }


            int parseResult;
            int.TryParse(vm.ComponentNumber.ToString(), out parseResult);
            if (parseResult <= 0)
            {
                ModelState.AddModelError(nameof(vm.SerialNo), "tast et positiv komponet component nummer");
            }

            if (ModelState.IsValid)
            {
                Category.ComponentStatus choosenComponentStatus;
                Enum.TryParse(vm.SelectedStatus, out choosenComponentStatus);

                _aesContext.Component.Add(new Category.Component
                {
                    AdminComment = vm.AdminComment,
                    ComponentNumber = vm.ComponentNumber,
                    SerialNo = vm.SerialNo,
                    Status = choosenComponentStatus,
                    ComponentTypeId = long.Parse(vm.SelectedComponentTypeId)

                });

                _aesContext.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                //Stay on page and try again.
                return View(CreateComponentViewModel());
            }
        }
    }
}

WebApplication4/src/WebApplication4/Views/Component/create.cshtml
@model WebApplication4.ViewModels.ComponentViewModel

@{
    ViewBag.Title = "Komponent";
}
<div class="row">

    <h2>Tilføj Kompoent</h2>

    <form asp-controller="Component" asp-action="Create" method="post" class="form-horizontal" role="form">
        <div class="form-horizontal">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-3">
                        <label>Komponent nummer </label>
                        <input asp-for="ComponentNumber" class="form-control" />
                        <span class="text-danger"></span>
                    </div>
                    <div class="col-md-3">
                        <label>Komponent serie nummer </label>
                        <input asp-for="SerialNo" class="form-control" />
                        <span class="text-danger"></span>
                    </div>
                    <div class="col-md-3">
                        <label>Admin kommentar </label>
                        <input asp-for="AdminComment" class="form-control" />
                        <span class="text-danger"></span>
                    </div>
                    <div class="col-md-3">
                        <label>Kompoent status</label> <br />
                        <select asp-for="SelectedStatus" asp-items="@Model.Status" class="dropdown">
                            <option>Please select one</option>
                        </select>
                        <span class="text-danger"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <label>KompoentType</label> <br />
                        <select asp-for="SelectedComponentTypeId" asp-items="@Model.ComponentTypeSelectListItems" class="dropdown">
                            <option>Please select one</option>
                        </select>
                        <span class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-5 col-md-12">
                    <input type="submit" value="Opret" class="btn btn-default" />
                </div>
            </div>
        </div>
    </form>
</div>

WebApplication4/src/WebApplication4/Views/Component/edit.cshtml
@model WebApplication4.ViewModels.ComponentViewModel

@{
    ViewBag.Title = "komponent";
}

<h2>Ændre komponentkategori</h2>

<div class="row">
    <form asp-controller="Component" asp-action="Edit" method="post" class="form-horizontal">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                </div>
                <div class="col-md-4 center-block">
                    <div class="form-group">
                        <label>Select komponent til ændring</label>
                        <br />
                        <select asp-for="SelectedComponentId" asp-items="@Model.ComponentsSelectListItems" class="form-control">
                            <option>Please select one</option>
                        </select>
                        <br />
                        <label>Status:</label>
                        <select asp-for="SelectedStatus" asp-items="@Model.Status" class="form-control">
                            <option>Please select one</option>
                        </select>
                        <br />
                        <label>SerialNo:</label>
                        <input asp-for="SerialNo" class="form-control" />
                        <br />
                        <label>Admin kommentar:</label>
                        <input asp-for="AdminComment" class="form-control" />
                        <br />
                        <label>KompoentType</label> <br />
                        <select asp-for="SelectedComponentTypeId" asp-items="@Model.ComponentTypeSelectListItems" class="dropdown">
                            <option>Please select one</option>
                        </select>
                        <span class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Ændre komponent" class="btn btn-default" />
                    </div>
                </div>
                <div class="col-md-4">
                </div>
            </div>
        </div>
    </form>
</div>

WebApplication4/src/WebApplication4/Views/Component/index.cshtml
@{
    ViewBag.Title = "komponenter";
}

<h2>komponenter</h2>

<div class="row">
    <div class="col-md-4">
        <a asp-action="Create">Tilføj komponent</a>
    </div>

    <div class="col-md-4">
        <a asp-action="Remove"> Fjern komponent</a>
    </div>

    <div class="col-md-4">
        <a asp-action="Edit">Ændre komponent</a>
    </div>
</div>

WebApplication4/src/WebApplication4/Views/Component/remove.cshtml
@model WebApplication4.ViewModels.ComponentViewModel

@{
    ViewBag.Title = "fjern Komponent";
}
<div class="row">
    <h2>Fjern Komponent</h2>
    <div class="row">
        <form asp-controller="Component" asp-action="Remove" method="post" class="form-horizontal" role="form">
            <div class="form-horizontal">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-offset-5 col-md-12">
                            <label>Kompoent</label> <br />
                            <select asp-for="SelectedComponentId" asp-items="@Model.ComponentsSelectListItems" class="dropdown">
                                <option>Please select one</option>
                            </select>
                            <span class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-offset-5 col-md-12">
                            <input type="submit" value="Fjern" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>