WebApplication4/src/WebApplication4/ViewModels/ComponentCategoryViewModel.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApplication4.Models
{
    public class ComponentCategoryViewModel
    {
        public int CategoryID { set; get; }
        public List<SelectListItem> Category { set; get; }
        public string NameChange { set; get; }
    }
}

WebApplication4/src/WebApplication4/Controllers/ComponentCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.DotNet.Cli.Utils;
using Microsoft.EntityFrameworkCore;
using WebApplication4.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace WebApplication4.Controllers
{
    [Authorize(Roles = "Admins")]
    public class ComponentCategoryController : Controller
    {

        private AesContext _aesContext;

        public ComponentCategoryController(AesContext aesContext)
        {
            _aesContext = aesContext;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admins")]
        public IActionResult Edit()
        {
            var categoryList = _aesContext.Category.AsNoTracking().ToList();
            var vm = new ComponentCategoryViewModel();
            vm.Category = new List<SelectListItem>();

            foreach (var category in categoryList)
            {
                vm.Category.Add(new SelectListItem
                {
                    Text = category.Name,
                    Value = category.CategoryId.ToString()
                });
            }
            return View(vm);
        }
        
        public IActionResult Remove()
        {
            var categoryList = _aesContext.Category.AsNoTracking().ToList();
            var vm = new ComponentCategoryViewModel();
            vm.Category = new List<SelectListItem>();

            foreach (var category in categoryList)
            {
                vm.Category.Add(new SelectListItem
                {
                    Text = category.Name,
                    Value = category.CategoryId.ToString()
                });
            }

            return View(vm);
        }

        [HttpPost]
        public IActionResult Remove(Category category)
        {

                if (ModelState.IsValid)
            {
                var firstOrDefault = _aesContext.Category.FirstOrDefault(b => b.CategoryId == category.CategoryId);
                _aesContext.Category.Remove(firstOrDefault);
                _aesContext.SaveChanges();
                    return RedirectToAction("Index");
                }

            return View();
        }

        [HttpPost]
        public IActionResult Edit(ComponentCategoryViewModel vm)
        {
            if (ModelState.IsValid)
            {
                var firstOrDefault = _aesContext.Category.FirstOrDefault(b => b.CategoryId == vm.CategoryID);
                firstOrDefault.Name = vm.NameChange;
                _aesContext.Category.Update(firstOrDefault);
                _aesContext.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpPost]
        public IActionResult Create(Category category)
        {
            if (!string.IsNullOrWhiteSpace(category.Name))
            {
                if (ModelState.IsValid)
                {
                    _aesContext.Category.Add(category);
                    _aesContext.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View();
        }
    }
}

WebApplication4/src/WebApplication4/Views/ComponentCategory/Index.cshtml
@model WebApplication4.Models.Category

@{
    ViewBag.Title = "komponentkategori";
}

<h2>komponentkategori</h2>

<div class="row">
    <div class="col-md-4">
        <a asp-action="Create">Tilføj komponentkategori</a>
    </div>

    <div class="col-md-4">
        <a asp-action="Remove"> Fjern komponentkategori </a>
    </div>

    <div class="col-md-4">
        <a asp-action="Edit">Ændre komponentkategori</a>
    </div>
</div>

WebApplication4/src/WebApplication4/Views/ComponentCategory/create.cshtml
@model WebApplication4.Models.Category

@{
    ViewBag.Title = "komponentkategori";
}

<h2>Tilføj komponentkategori</h2>

<div class="row">

    <form asp-controller="ComponentCategory" asp-action="Create" method="post" class="form-horizontal" role="form">
        <div class="form-horizontal">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Name" class="form-control" />
                    <span class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Opret" class="btn btn-default" />
                </div>
            </div>
        </div>
    </form>
</div>

WebApplication4/src/WebApplication4/Views/ComponentCategory/edit.cshtml
@model WebApplication4.Models.ComponentCategoryViewModel

@{
    ViewBag.Title = "komponentkategori";
}

<h2>Ændre komponentkategori</h2>

<div class="row">
    <form asp-controller="ComponentCategory" asp-action="Edit" method="post" class="form-horizontal">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                </div>
                <div class="col-md-4 center-block">
                    <div class="form-group">
                        <label>Select Kategori til ændring</label>
                        <br />
                        <select asp-for="CategoryID" asp-items="@Model.Category" class="form-control">
                            <option>Please select one</option>
                        </select>
                        <br />
                        <label>Ændring</label>
                        <input asp-for="NameChange" class="form-control" />
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Ændre komponentkategori" class="btn btn-default" />
                    </div>
                </div>
                <div class="col-md-4">
                </div>
            </div>
        </div>
    </form>
</div>

WebApplication4/src/WebApplication4/Views/ComponentCategory/remove.cshtml
@model WebApplication4.Models.ComponentCategoryViewModel

@{
    ViewBag.Title = "komponentkategori";
}

<h2>komponentkategori</h2>
<div class="row">
    <form asp-controller="ComponentCategory" asp-action="Remove" method="post" class="form-horizontal">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                </div>
                <div class="col-md-4 center-block">
                    <div class="form-group">
                        <select asp-for="CategoryID" asp-items="@Model.Category" class="dropdown">
                            <option>Please select one</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Fjern komponentkategori" class="btn btn-default" />
                    </div>
                </div>
                <div class="col-md-4">
                </div>
            </div>
        </div>
    </form>
</div>