WebApplication4/src/WebApplication4/ViewModels/ComponentTypeViewModel.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApplication4.ViewModels
{
    public class ComponentTypeViewModel
    {
        public long ComponentTypeId { get; set; }
        public string ComponentName { get; set; }
        public string ComponentInfo { get; set; }
        public string Location { get; set; }
        public string Datasheet { get; set; }
        public string ImageUrl { get; set; }

        public string Manufacturer { get; set; }
        public string WikiLink { get; set; }

        public string AdminComment { get; set; }

        public List<SelectListItem> ComponentStatuSelectListItems { set; get; }

        public string SelectedStatus { get; set; }

        public List<SelectListItem> CategorySelectListItems { set; get; }

        public string SelectedCategoryId { get; set; }

    }
}

WebApplication4/src/WebApplication4/Controllers/ComponentTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication4.Models;
using WebApplication4.ViewModels;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace WebApplication4.Controllers
{
    [Authorize(Roles = "Admins")]
    public class ComponentTypeController : Controller
    {
        private AesContext _aesContext;
        public ComponentTypeController(AesContext aesContext)
        {
            _aesContext = aesContext;
        }
        [AllowAnonymous]
        public IActionResult Index()
        {

            var vm = new ComponentTypeViewModel();
            vm.ComponentStatuSelectListItems = new List<SelectListItem>();
            vm.CategorySelectListItems = new List<SelectListItem>();

            foreach (var Category in _aesContext.Category)
            {
                vm.CategorySelectListItems.Add(new SelectListItem
                {
                    Text = Category.Name,
                    Value = Category.CategoryId.ToString()
                });
            }

            foreach (String status in Enum.GetNames(typeof(Category.ComponentTypeStatus)))
            {
                vm.ComponentStatuSelectListItems.Add(new SelectListItem
                {
                    Text = status,
                    Value = status
                });
            }

            return View(vm);
        }

        [HttpPost]
        public IActionResult Create(ComponentTypeViewModel vm)
        {
            Category.ComponentTypeStatus choosenComponentTypeStatus;
            Enum.TryParse(vm.SelectedStatus, out choosenComponentTypeStatus);

            _aesContext.ComponentType.Add(new Category.ComponentType
            {
                ComponentName = vm.ComponentName,
                ComponentInfo = vm.ComponentInfo,
                Location = vm.Location,
                Status = choosenComponentTypeStatus,
                Datasheet = vm.Datasheet,
                ImageUrl = vm.ImageUrl,
                Manufacturer = vm.Manufacturer,
                WikiLink = vm.WikiLink,
                AdminComment = vm.AdminComment
                
            });
            _aesContext.SaveChanges();

            //Make link between type and category

            var findCompoentType = from b in _aesContext.ComponentType
                where b.ComponentName == vm.ComponentName
                select b;

            var findCatagory = from b in _aesContext.Category
                where b.CategoryId == int.Parse(vm.SelectedCategoryId)
                select b;

            _aesContext.CategoryComponentType.Add(new CategoryComponentType
            {
                Category = findCatagory.FirstOrDefault(),
                CategoryId = findCatagory.FirstOrDefault().CategoryId,

                ComponentType = findCompoentType.FirstOrDefault(),
                ComponentTypesId = int.Parse(findCompoentType.FirstOrDefault().ComponentTypeId.ToString())
            });
            _aesContext.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebApplication4/src/WebApplication4/Views/ComponentType/Index.cshtml
@model WebApplication4.ViewModels.ComponentTypeViewModel

@{
    ViewBag.Title = "Tilføj KomponentType";
}

<h2>Tilføj KomponentType</h2>
<div class="row">
    <form asp-controller="ComponentType" asp-action="Create" method="post" class="form-horizontal" role="form">
        <div class="form-horizontal">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-3">
                        <label>Komponent navn </label>
                        <input asp-for="ComponentName" class="form-control" />
                        <span class="text-danger"></span>
                    </div>
                    <div class="col-md-3">
                        <label>Komponent info </label>
                        <input asp-for="ComponentInfo" class="form-control" />
                        <span class="text-danger"></span>
                    </div>
                    <div class="col-md-3">
                        <label>lokation </label>
                        <input asp-for="Location" class="form-control" />
                        <span class="text-danger"></span>
                    </div>
                    <div class="col-md-3">
                        <label>Komponent Type Status</label> <br />
                        <select asp-for="SelectedStatus" asp-items="@Model.ComponentStatuSelectListItems" class="dropdown">
                            <option>Please select one</option>
                        </select>
                        <span class="text-danger"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <label>Datablad </label>
                        <input asp-for="Datasheet" class="form-control" />
                        <span class="text-danger"></span>
                    </div>
                    <div class="col-md-3">
                        <label>billede addresse </label>
                        <input asp-for="ImageUrl" class="form-control" />
                        <span class="text-danger"></span>
                    </div>
                    <div class="col-md-3">
                        <label>producent </label>
                        <input asp-for="Manufacturer" class="form-control" />
                        <span class="text-danger"></span>
                    </div>
                    <div class="col-md-3">
                        <label>wiki link </label>
                        <input asp-for="WikiLink" class="form-control" />
                        <span class="text-danger"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <label>admin kommentar </label>
                        <input asp-for="AdminComment" class="form-control" />
                        <span class="text-danger"></span>
                    </div>
                    <div class="col-md-3">
                        <label>Tilhørende kategori</label> <br />
                        <select asp-for="SelectedCategoryId" asp-items="@Model.CategorySelectListItems" class="dropdown">
                            <option>Please select one</option>
                        </select>
                        <span class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-5 col-md-12">
                    <input type="submit" value="Opret" class="btn btn-default" />
                </div>
            </div>
        </div>
    </form>
</div>