WebApplication4/src/WebApplication4/ViewModels/FindComponentTypeInCategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApplication4.ViewModels
{
    public class FindComponentTypeInCategory
    {
        public String SelectCategoryId { set; get; }
        public List<SelectListItem> CategorySelectListItems { set; get; }
    }
}

WebApplication4/src/WebApplication4/Controllers/ViewDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication4.Models;
using WebApplication4.ViewModels;

namespace WebApplication4.Controllers
{
    public class ViewDataController : Controller
    {
        private readonly AesContext _aesContext;

        public ViewDataController(AesContext aesContext)
        {
            _aesContext = aesContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult FindCompoentInComponentType()
        {
            var vm = new FindCompoentInComponentTypeViewModel();
            vm.CompoentTypeSelectListItems = new List<SelectListItem>();

            foreach (var componentType in _aesContext.ComponentType.AsNoTracking().ToList())
            {
                vm.CompoentTypeSelectListItems.Add(new SelectListItem
                {
                    Text = componentType.ComponentName,
                    Value = componentType.ComponentTypeId.ToString()
                });
            }

            return View(vm);
        }
        public IActionResult FindComponentTypeInCategory()
        {
            var vm = new FindComponentTypeInCategory();
            vm.CategorySelectListItems = new List<SelectListItem>();

            foreach (var Category in _aesContext.Category.AsNoTracking().ToList())
            {
                vm.CategorySelectListItems.Add(new SelectListItem
                {
                    Text = Category.Name,
                    Value = Category.CategoryId.ToString()
                });
            }
            return View(vm);
        }
        [HttpPost]
        public IActionResult FindComponentTypeInCategoryResult(FindComponentTypeInCategory vm)
        {
            var result = from b in _aesContext.CategoryComponentType where b.Category.CategoryId == int.Parse(vm.SelectCategoryId) select b.ComponentType;

            return View(result.AsNoTracking());
        }

        public IActionResult SearchComponent()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SearchComponentResult(searchViewModel vm)
        {
            var result = from b in _aesContext.Component
                         where b.SerialNo.StartsWith(vm.searchKeyword)
                         select b;

            return View(result.AsNoTracking());
        }

        [HttpPost]
        public IActionResult FindCompoentInComponentTypeResult(FindCompoentInComponentTypeViewModel vm)
        {
            //This was chage to improve performence 
            /*
            var t = _aesContext.ComponentType.ToList();

            //Bad runs the query client site and not server site because of AsEnumerable
            var findLinks = from b in _aesContext.CategoryComponentType.AsEnumerable()
                            where b.CategoryId.Equals(int.Parse(vm.SelectCategoryId))
                            select b;

            var links = findLinks.ToList();

            var result = new List<Category.ComponentType>();

            foreach (var component in links)
            {
                foreach (var type in t)
                {
                    if (component.ComponentTypesId == type.ComponentTypeId)
                    {
                        result.Add(type);
                    }
                }
            } */

            var result = from b in _aesContext.Component where b.ComponentTypeId.Equals(long.Parse(vm.SelectCompoentTypeId)) select b;

            return View(result.AsNoTracking());
        }
    }
}

WebApplication4/src/WebApplication4/Views/ViewData/FindCompoentInComponentType.cshtml
@model WebApplication4.ViewModels.FindCompoentInComponentTypeViewModel

@{
    ViewBag.Title = "Find Komponent Type i compoent katagori";
}

<h2>Find Komponent Type i compoent katagori</h2>
<form asp-controller="ViewData" asp-action="FindCompoentInComponentTypeResult" method="post" class="form-horizontal" role="form">
    <div class="form-horizontal">
    <div class="form-group">
        <div class="row">
            <div class="col-md-3">
                <label>Komponent Type Status</label> <br />
                <select asp-for="SelectCompoentTypeId" asp-items="@Model.CompoentTypeSelectListItems" class="dropdown">
                    <option>Please select one</option>
                </select>
                <span class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="form-group">
                <div class="col-md-offset-5 col-md-12">
                    <input type="submit" value="find" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
</div>
</form>

WebApplication4/src/WebApplication4/Views/ViewData/FindCompoentInComponentTypeResult.cshtml
@model IEnumerable<WebApplication4.Models.Category.Component>

@{
    ViewBag.Title = "Se resultatet af søgning på componenter i en given component type";
}

<h2>Find Komponent Type i compoent katagori</h2>

<div>

    <div class="row">
        <div class="col-md-3">
            <label >SerialNo</label>
        </div>
        <div class="col-md-3">
            <label >ComponentNumber </label>
        </div>
        <div class="col-md-3">
            <label>AdminComment </label>
        </div>
        <div class="col-md-3">
            <label>Status</label>
        </div>
    </div>

    @foreach (var item in Model)
    {
        <div class="row">
            <div class="col-md-3">
                <p>@item.SerialNo</p>
            </div>
            <div class="col-md-3">
                <p>@item.ComponentNumber</p>
            </div>
            <div class="col-md-3">
                <p>@item.AdminComment</p>
            </div>
            <div class="col-md-3">
                <p>@item.Status</p>
            </div>
        </div>
    }
</div>

WebApplication4/src/WebApplication4/Views/ViewData/FindComponentTypeInCategory.cshtml
    @model WebApplication4.ViewModels.FindComponentTypeInCategory

    @{
        ViewBag.Title = "Find Komponent Type i compoent katagori";
    }

    <h2>Find KomponentType i Kategorier</h2>
    <form asp-controller="ViewData" asp-action="FindComponentTypeInCategoryResult" method="post" class="form-horizontal" role="form">
        <div class="form-horizontal">
        <div class="form-group">
            <div class="row">
                <div class="col-md-3">
                    <label>Komponent Type Status</label> <br />
                    <select asp-for="SelectCategoryId" asp-items="@Model.CategorySelectListItems" class="dropdown">
                        <option>Please select one</option>
                    </select>
                    <span class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <div class="col-md-offset-5 col-md-12">
                        <input type="submit" value="find" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    </form>

WebApplication4/src/WebApplication4/Views/ViewData/FindComponentTypeInCategoryResult.cshtml
@model IEnumerable<WebApplication4.Models.Category.ComponentType>

@{
    ViewBag.Title = "Se resultatet af søgning på componenter i en given component type";
}

<h2>Find Komponent Type i compoent katagori</h2>

<div>

    <div class="row">
        <div class="col-md-2">
            <label>Komponent navn</label>
        </div>
        <div class="col-md-2">
            <label>Info </label>
        </div>
        <div class="col-md-2">
            <label>WikiLink </label>
        </div>
        <div class="col-md-2">
            <label>Lokation</label>
        </div>
        <div class="col-md-2">
            <label>fremstillet af</label>
        </div>
        <div class="col-md-2">
            <label>admin kommentar</label>
        </div>
    </div>

    @foreach (var item in Model)
    {
        <div class="row">
            <div class="col-md-2">
                <p>@item.ComponentName</p>
            </div>
            <div class="col-md-2">
                <p>@item.ComponentInfo</p>
            </div>
            <div class="col-md-2">
                <p>@item.WikiLink</p>
            </div>
            <div class="col-md-2">
                <p>@item.Location</p>
            </div>
            <div class="col-md-2">
                <p>@item.Manufacturer</p>
            </div>
            <div class="col-md-2">
                <p>@item.AdminComment</p>
            </div>
        </div>
    }
</div>

WebApplication4/src/WebApplication4/Views/ViewData/Index.cshtml
@model WebApplication4.Models.Category

@{
    ViewBag.Title = "Se data";
}

<h2>komponentkategori</h2>

<div class="row">
    <div class="col-md-4">
        <a asp-action="FindCompoentInComponentType">Find Komponent i komponent Type</a>
    </div>

    <div class="col-md-4">
        <a asp-action="FindComponentTypeInCategory"> Find komponentType i komponentkategori </a>
    </div>

    <div class="col-md-4">
        <a asp-action="SearchComponent">Søg komponent</a>
    </div>
</div>

WebApplication4/src/WebApplication4/Views/ViewData/SearchComponent.cshtml
@model WebApplication4.ViewModels.searchViewModel

@{
    ViewBag.Title = "Find Komponent Type i compoent katagori";
}

<h2>Find Komponent Via SerieNummer</h2>

<form asp-controller="ViewData" asp-action="SearchComponentResult" method="post" class="form-horizontal" role="form">
    <div class="form-horizontal">
        <div class="form-group">
            <div class="row">
                <div class="col-md-3">
                    <label>Komponent Type Status</label> <br />
                    <input asp-for="searchKeyword" class="form-control" />    
                    <span class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <div class="col-md-offset-5 col-md-12">
                        <input type="submit" value="find" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

WebApplication4/src/WebApplication4/Views/ViewData/SearchComponentResult.cshtml
@model IEnumerable<WebApplication4.Models.Category.Component>

@{
    ViewBag.Title = "Se resultatet af søgning på componenter i en given component type";
}

<h2>Komponenter : Søgnings Resultat</h2>

<div class="row">
    <div class="col-md-3">
        <label>SerialNo</label>
    </div>
    <div class="col-md-3">
        <label>ComponentNumber </label>
    </div>
    <div class="col-md-3">
        <label>AdminComment </label>
    </div>
    <div class="col-md-3">
        <label>Status</label>
    </div>
</div>

@foreach (var item in Model)
{
    <div class="row">
        <div class="col-md-3">
            <p>@item.SerialNo</p>
        </div>
        <div class="col-md-3">
            <p>@item.ComponentNumber</p>
        </div>
        <div class="col-md-3">
            <p>@item.AdminComment</p>
        </div>
        <div class="col-md-3">
            <p>@item.Status</p>
        </div>
    </div>
}